version: "3.8"
services:
  rust:
    image: rust:1.54.0-buster
    working_dir: /opt/app
    volumes:
      - ./wasm_filter:/opt/app
    tty: true
    command: "./compile.sh"

  backend:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
     - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    volumes:
      - ./mockserver/initializer.json:/config/initializer.json

  envoy:
    image: envoyproxy/envoy:v1.20.0
    entrypoint: "bash -c"
    command: "'while [ ! -f /etc/envoy/target/wasm32-unknown-unknown/release/content_type.wasm ]; do sleep 1; done && envoy -c /etc/envoy/envoy.yaml --component-log-level wasm:debug'"
    volumes:
      - ./envoy_example/config.yaml:/etc/envoy/envoy.yaml
      - ./wasm_filter/target:/etc/envoy/target
    ports:
      - "1000:1000"
      - "2000:2000"
      - "9901:9901"
